{
  "formatVersion": "1.1",
  "component": {
    "group": "io.admize.sdk.android",
    "module": "admize-sdk-android-uat",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-android-uat-1.0.5.aar",
          "url": "admize-sdk-android-uat-1.0.5.aar",
          "size": 1204791,
          "sha512": "00bce6aa1a493b87830d960d588cfbb97bd75f2336b22eb4ca4a630ba32254ede0f194a45f6c4b5d97a46c5a286a1e1dfbc30f43e44b3bb135ca37b496b2f716",
          "sha256": "4917ea136e9aceaf9f9d25ef5fe2ba4f50c659683a8e8b6fda9caf1a8d085b0a",
          "sha1": "e6c8c5ef5f4bbab7c4a4a97a69693356d8490620",
          "md5": "af7b9264706bc4b05c3997eaae0fbecb"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-android-uat-1.0.5.aar",
          "url": "admize-sdk-android-uat-1.0.5.aar",
          "size": 1204791,
          "sha512": "00bce6aa1a493b87830d960d588cfbb97bd75f2336b22eb4ca4a630ba32254ede0f194a45f6c4b5d97a46c5a286a1e1dfbc30f43e44b3bb135ca37b496b2f716",
          "sha256": "4917ea136e9aceaf9f9d25ef5fe2ba4f50c659683a8e8b6fda9caf1a8d085b0a",
          "sha1": "e6c8c5ef5f4bbab7c4a4a97a69693356d8490620",
          "md5": "af7b9264706bc4b05c3997eaae0fbecb"
        }
      ]
    }
  ]
}
