{
  "formatVersion": "1.1",
  "component": {
    "group": "io.admize.sdk.android",
    "module": "admize-sdk-android",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-android-1.0.5.aar",
          "url": "admize-sdk-android-1.0.5.aar",
          "size": 1145950,
          "sha512": "8b76f5fb8bf43adc4f4c45300082706fe5e5c4321c4526743a4a7517e0c38e821416789db62bc304e6f1fb8048b7ac175d8c1ba5b8a34abbe0b031595d2d1f13",
          "sha256": "218d11b8dfd07ab1d1276c5fedd1aade7c196e5c253ff0a33f84d785a920b8aa",
          "sha1": "d6c86eb033c576cc8a2b37c6ebb2bddce3fae64b",
          "md5": "451aa2ee748e340783d83db37066d299"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-android-1.0.5.aar",
          "url": "admize-sdk-android-1.0.5.aar",
          "size": 1145950,
          "sha512": "8b76f5fb8bf43adc4f4c45300082706fe5e5c4321c4526743a4a7517e0c38e821416789db62bc304e6f1fb8048b7ac175d8c1ba5b8a34abbe0b031595d2d1f13",
          "sha256": "218d11b8dfd07ab1d1276c5fedd1aade7c196e5c253ff0a33f84d785a920b8aa",
          "sha1": "d6c86eb033c576cc8a2b37c6ebb2bddce3fae64b",
          "md5": "451aa2ee748e340783d83db37066d299"
        }
      ]
    }
  ]
}
