{
  "formatVersion": "1.1",
  "component": {
    "group": "io.admize.sdk.android",
    "module": "admize-sdk-android-uat",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-android-uat-1.0.1.aar",
          "url": "admize-sdk-android-uat-1.0.1.aar",
          "size": 1204463,
          "sha512": "8f76293f823cfe809316bf037bac206b20e6453b787d0a7c1842409e58e3d458c4eaa431fd694ce35f8ee569d7e20140b70541007c0cc3ce0ee3a07915c1eb1c",
          "sha256": "f12030ad2552e2f484011f453821347705c1f5cb63a0392a371bb4a6b6211d38",
          "sha1": "b45fad9cc4b8feba7b8af36598888bd534d430fe",
          "md5": "713cf483cfd9e9e3b905947f31c2b1aa"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-android-uat-1.0.1.aar",
          "url": "admize-sdk-android-uat-1.0.1.aar",
          "size": 1204463,
          "sha512": "8f76293f823cfe809316bf037bac206b20e6453b787d0a7c1842409e58e3d458c4eaa431fd694ce35f8ee569d7e20140b70541007c0cc3ce0ee3a07915c1eb1c",
          "sha256": "f12030ad2552e2f484011f453821347705c1f5cb63a0392a371bb4a6b6211d38",
          "sha1": "b45fad9cc4b8feba7b8af36598888bd534d430fe",
          "md5": "713cf483cfd9e9e3b905947f31c2b1aa"
        }
      ]
    }
  ]
}
