{
  "formatVersion": "1.1",
  "component": {
    "group": "io.admize.sdk.android",
    "module": "admize-sdk-android-uat",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-android-uat-1.0.7.aar",
          "url": "admize-sdk-android-uat-1.0.7.aar",
          "size": 1177554,
          "sha512": "9d400ccf08ca5ee5bce707736465886a61f9a10c0dd79ee68ee48b1a16a164e8879a81bf6bfb7d83ea0f2bdbffe88d088a5c1c206a688728e63756ac6ab19b45",
          "sha256": "08f48bfc700abfb3cc5c1404daf30b5bbfc984cf486edac1d813ddf0ba5661c7",
          "sha1": "34cbb282cdb8089cc089e9ef9e4971cc1f0ecb1f",
          "md5": "6587dc3a68519c5c4ea547cc25c51dd5"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-android-uat-1.0.7.aar",
          "url": "admize-sdk-android-uat-1.0.7.aar",
          "size": 1177554,
          "sha512": "9d400ccf08ca5ee5bce707736465886a61f9a10c0dd79ee68ee48b1a16a164e8879a81bf6bfb7d83ea0f2bdbffe88d088a5c1c206a688728e63756ac6ab19b45",
          "sha256": "08f48bfc700abfb3cc5c1404daf30b5bbfc984cf486edac1d813ddf0ba5661c7",
          "sha1": "34cbb282cdb8089cc089e9ef9e4971cc1f0ecb1f",
          "md5": "6587dc3a68519c5c4ea547cc25c51dd5"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admize-sdk-android-uat-1.0.7-sources.jar",
          "url": "admize-sdk-android-uat-1.0.7-sources.jar",
          "size": 103578,
          "sha512": "d3edd7f24d826385e441ae695428c4e693065faad725af7082cc405e92ca306a222b4764e3858a2fde9db816d2413c491e94c1977a9aefc206cfa5d1e3a9f958",
          "sha256": "78f04cda0d92c0b5c802591248b5cc8f12c5fe1cfe69b341b5e07cbe75091bd3",
          "sha1": "21baca175fe8cd62401a75234f694e74827c28b9",
          "md5": "90680d4594cceb1fce1d9d87b78b40e6"
        }
      ]
    }
  ]
}
