{
  "formatVersion": "1.1",
  "component": {
    "group": "io.admize.sdk.android",
    "module": "admize-sdk-android-uat",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "uatDebugVariantUatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-android-uat-1.0.7.aar",
          "url": "admize-sdk-android-uat-1.0.7.aar",
          "size": 1177563,
          "sha512": "e349badb193bdad981bf7829bf01bf3ad263baba237113bfad6640398c36751ea0aa206ba34a0cc8d17469285b278ec9ff676512c5c3789261ff1afedd1cf84c",
          "sha256": "b72cd621b00f69ded98dbf59ea2ce308381326db103dff046279981a96012dbd",
          "sha1": "440f80bed31a4fa4733b62a924141b63c21d6890",
          "md5": "28929c354f2813266355dd51a67b3937"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-android-uat-1.0.7.aar",
          "url": "admize-sdk-android-uat-1.0.7.aar",
          "size": 1177563,
          "sha512": "e349badb193bdad981bf7829bf01bf3ad263baba237113bfad6640398c36751ea0aa206ba34a0cc8d17469285b278ec9ff676512c5c3789261ff1afedd1cf84c",
          "sha256": "b72cd621b00f69ded98dbf59ea2ce308381326db103dff046279981a96012dbd",
          "sha1": "440f80bed31a4fa4733b62a924141b63c21d6890",
          "md5": "28929c354f2813266355dd51a67b3937"
        }
      ]
    },
    {
      "name": "uatDebugVariantUatDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admize-sdk-android-uat-1.0.7-sources.jar",
          "url": "admize-sdk-android-uat-1.0.7-sources.jar",
          "size": 103578,
          "sha512": "66cf0bbf79419ace68b3cbdcc7c92f9b4e3b2babf85421c6d7585646cb5d5b7ce310af47378af2a9ca4fbf938d36afd72093307487ccb100d7e53bbf912d5f92",
          "sha256": "9442aff34816006aca9f6b0143a6884e203f18a9ec548a761383d3af9af3c648",
          "sha1": "818628ec975bd1e6be9c7b91248ee3ee99c699a4",
          "md5": "39149105437a209ea5cfceda7bf26f1e"
        }
      ]
    }
  ]
}
